### ISSUE TITLE
If read Chinese Paper, this Library cannot display text, but Zotero beta7 can

### ISSUE THREAD

**Issue by ClearLuvMoki** [zotero/reader#109]
**READ THIS BEFORE CREATING AN ISSUE**

Zotero does not use GitHub Issues for bug reports or feature requests.

Please post all such requests to the Zotero Forums at https://forums.zotero.org, where Zotero developers and many others can help. For confirmed bugs or agreed-upon changes, Zotero developers will create new issues in the relevant repositories.

Development questions involving code, APIs, or other technical topics can be posted to the zotero-dev mailing list at http://groups.google.com/group/zotero-dev.

See https://www.zotero.org/support/zotero_support for more information on how Zotero support works.

**Comment by ClearLuvMoki** [comment]
![image](https://github.com/zotero/reader/assets/61321768/bac213c6-7256-4dab-9948-afd677042bcf)

**Comment by dstillman** [comment]
As it says in the issue template, all support requests should be posted to the Zotero Forums.

**Comment by dstillman** [comment]
Please stop posting across all of our channels. Again, we provide support in the Zotero Forums. If you want help, you'll need to post there — not here, not the dev list.
